name: docker_builds

on:
#  pull_request:
#    branches:
#      - develop
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-push-linux-image:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/ubuntu
          push: true
          tags: ghcr.io/nonameentername/godot-vst3host-ubuntu:${{ env.VERSION }},ghcr.io/nonameentername/godot-vst3host-ubuntu:latest

  build-and-push-windows-image:
    name: Windows (MinGW)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/mingw
          push: true
          tags: ghcr.io/nonameentername/godot-vst3host-mingw:${{ env.VERSION }},ghcr.io/nonameentername/godot-vst3host-mingw:latest

  build-and-push-macos-image:
    name: MacOS (osxcross)
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: platform/osxcross
          push: true
          tags: ghcr.io/nonameentername/godot-vst3host-osxcross:${{ env.VERSION }},ghcr.io/nonameentername/godot-vst3host-osxcross:latest
